name: Terraform Plan ETL
run-name: octonomy-${{ inputs.environment }}-terraform-plan-etl

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment (dev or test or stage or prod)'
        type: choice
        required: true
        options:
          - dev
          - test
          - stage
          - prod

jobs:
  Terraform_Plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      TF_VAR_ARGUN_AUTH_TOKEN: ${{ secrets.TF_VAR_ARGUN_AUTH_TOKEN}}
      TF_VAR_DBMS_AUTH_TOKEN: ${{ secrets.TF_VAR_DBMS_AUTH_TOKEN }}
      TF_VAR_ETL_AUTH_TOKEN: ${{ secrets.TF_VAR_ETL_AUTH_TOKEN }}
      TF_VAR_INTEG_AUTH_TOKEN: ${{ secrets.TF_VAR_INTEG_AUTH_TOKEN }}
      TF_VAR_SCH_AUTH_TOKEN: ${{ secrets.TF_VAR_SCH_AUTH_TOKEN }}
      TF_VAR_API_ENDPOINT: ${{ secrets.TF_VAR_API_ENDPOINT }}
      TF_VAR_C4_DB_PASSWORD: ${{ secrets.C4_DB_PASSWORD }}
      TF_VAR_C5_DB_PASSWORD: ${{ secrets.C5_DB_PASSWORD }}
      TF_VAR_C6_DB_PASSWORD: ${{ secrets.C6_DB_PASSWORD }}
      TF_VAR_C13_DB_PASSWORD: ${{ secrets.C13_DB_PASSWORD }}
      TF_VAR_C14_DB_PASSWORD: ${{ secrets.C14_DB_PASSWORD }}
      TF_VAR_COMMON_DB_PASSWORD: ${{ secrets.COMMON_DB_PASSWORD }}
      TF_VAR_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Download Step Functions
        if: ${{ github.event.inputs.environment == 'dev' || github.event.inputs.environment == 'stage' || github.event.inputs.environment == 'prod' }}
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          export AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
          export Environment=${{ github.event.inputs.environment }}
          python .github/workflows/download_step_functions.py

      - name: Terraform Init
        run: |
          cd etl/
          terraform init -backend-config="key=${{ vars.KEY_ETL }}"
          
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd etl/
          terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars -out=qs-${{ github.event.inputs.environment }}-plan
