name: Site2Site VPN Terraform Apply
run-name: Site2Site-VPN-${{ inputs.site2site_vpn_name }}-terraform-apply

on:
  workflow_dispatch:
    inputs:
      site2site_vpn_name:
        description: 'Site2Site VPN name (e.g., wenko-stage-proxy)'
        type: string
        required: true

jobs:
  Terraform_Apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Validate Site2Site VPN Directory
        run: |
          if [ ! -d "site2site-vpn/${{ github.event.inputs.site2site_vpn_name }}" ]; then
            echo "Error: Directory site2site-vpn/${{ github.event.inputs.site2site_vpn_name }} does not exist"
            exit 1
          fi
          echo "Validated directory: site2site-vpn/${{ github.event.inputs.site2site_vpn_name }}"

      - name: Terraform Init
        run: |
          cd site2site-vpn/${{ github.event.inputs.site2site_vpn_name }}
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd site2site-vpn/${{ github.event.inputs.site2site_vpn_name }}
          terraform validate

      - name: Terraform Apply
        id: apply
        run: |
          cd site2site-vpn/${{ github.event.inputs.site2site_vpn_name }}
          terraform apply -var-file=${{ github.event.inputs.site2site_vpn_name }}.tfvars --auto-approve

